# Spring Datasource Configuration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: cisco
  jpa:
    properties:
      hibernate:
        default_schema: public
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: create

# Spring MVC Configuration


# Server Configuration
server:
  port: 8080  # You can change the port as needed
